### ISSUE TITLE
Problem with downloader.py

### ISSUE THREAD

**Issue by UrielMendoza** [pereira-gha/activefire#1]
When running the downloader.py I get this error, I don't know if it has to do with the pandas version, I'm running it with the pandas version 0.23.3

Traceback (most recent call last):
  File "downloader.py", line 39, in <module>
    for ind,image_name in enumerate(df.productId.to_list()):
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 4378, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'to_list'

**Comment by UrielMendoza** [comment]
Update pandas version and it worked.

**Comment by UrielMendoza** [comment]
Update pandas version and it worked
